### ISSUE TITLE
Errors on add an item on main page

### ISSUE THREAD

**Issue by andkirby** [openpim/web#1]
Hi,

Not sure if I should mention this issue here...
It looks like there is an issue on main page.

1. Go to http://demo.openpim.org/ and login with `demo`/`demo`.
2. In section with Data - Product Data, etc., click on ➕

**Actual**
Nothing happens. In console:
```
Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'en')
``` 

**Expected**
Some right action without errors.

**Comment by openpim** [comment]
Hi,

Thanks for submitting this issue we will work on this.

But in common you are not able to add something with the demo account. You should receive the error: "Impossible to create children for ..." because "demo" user can not edit or create something.
So even if we fix the issue you will not be able to make something at http://demo.openpim.org/.

But you can run demo locally as described at our site and then you will be able to make changes with the user "admin" with password "admin". By the way, we have more recent version for local demo, so this issue can be already solved there.

Thanks,
Slava Pedak

**Comment by andkirby** [comment]
Hi @openpim ,
Understood. Thanks for the quick answer.

**Comment by openpim** [comment]
fixed
